### ISSUE TITLE
ERROR: Package u'cc-net' requires a different Python: 2.7.12 not in '>=3.7'

### ISSUE THREAD

**Issue by Nanamumuhan** [facebookresearch/cc_net#12]
![图片](https://user-images.githubusercontent.com/41236260/92096846-f4f47800-ee09-11ea-81c0-786ccd37b0bb.png)

**Comment by Nanamumuhan** [comment]
how to solve this

**Comment by gwenzek** [comment]
it seems you're using python2.7 which is not supported.
You should run this with python3.
You should either use `conda` or `venv`

For example
```sh
python3 -m venv
. venv/bin/activate
python --version
make install
```
