### ISSUE TITLE
Doing hashing, mining and regroup from each bin order

### ISSUE THREAD

**Issue by aswin-giridhar** [facebookresearch/cc_net#15]
Hi,

Sorry, but I think I might have missed reading regarding this but I am trying to get all the json files once the hash bin files are created instead of waiting for all the hash bin to be downloaded and then the mining is done. Is there a way to go about it.

Thanks in advance,
Aswin

**Comment by gwenzek** [comment]
> all the hash bin to be downloaded

Hashes files are not downloaded they are computed.
They are used for doing deduplications.
First we compute the hashes for all the paragraphs, then we remove paragraphs who have duplicates.
There is no way to start deduplication before all the hashes are computed.

If you want something which is lighter, you can look at: https://github.com/facebookresearch/cc_net#reproducing-our-work
