### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by alexandremuzio** [facebookresearch/cc_net#3]
After running `make install`, I was getting 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/alferre/cc_net/cc_net/__main__.py", line 11, in <module>
    import cc_net.mine
  File "/data1/alferre/cc_net/cc_net/mine.py", line 29, in <module>
    from cc_net import dedup, execution, jsonql, perplexity, process_wet_file
  File "/data1/alferre/cc_net/cc_net/dedup.py", line 25, in <module>
    from cc_net import jsonql
  File "/data1/alferre/cc_net/cc_net/jsonql.py", line 50, in <module>
    from typing_extensions import Literal, Protocol
```

Running `pip install typing_extensions` fixed it. So this package is probably missing from the setup.py.

**Comment by gwenzek** [comment]
Thanks for reporting. Fixed

**Comment by raldawiyahh** [comment]
thanks for fixing the problem

**Comment by fayizv** [comment]
thanks for the information

**Comment by ITIgit** [comment]
I am facing from "typing_extensions import Required, Self ModuleNotFoundError: No module named 'typing_extensions' error".
It is working fine.
Thank you

**Comment by mohamedGaber93** [comment]
Please how can i fixed that in pycharm when i useing odoo16

line 55, in <module>
    from typing_extensions import TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'

Process finished with exit code 1
