### ISSUE TITLE
Dedup all paragraphs if it appear more than once?

### ISSUE THREAD

**Issue by xingenju** [facebookresearch/cc_net#8]
eg. if "it is an issue about cc_net" is a paragraph and it appeared three times, as the NativeHashSet saves the value of this key is 1, the 3 paragraphs will be dropped. Why not save one copy?

**Comment by gwenzek** [comment]
The decision may seems weird, but when looking at the data it appeared that most duplicate  paragraph was either:

* very short sentences, in which case the sentence is likely to appear somewhere else inside a paragraph
* menu elements that appear across a whole website
* boilerplate like cookie warnings which are presents on a lot of websites

Therefore I chose to not include them.
But I agree this decision isn't really documented in the paper, and could be worth some experiments.

**Comment by gwenzek** [comment]
Closing, feel free to reopen if I haven't fully answered your questions.
