### ISSUE TITLE
support of Hausa

### ISSUE THREAD

**Issue by donglixp** [facebookresearch/cc_net#9]
Thanks for your contribution to the community. I am wondering whether the ccnet contains the `Hausa` language (ISO id: ha/hau)? Because in [the xlm-r paper](https://arxiv.org/pdf/1911.02116.pdf), Table 6 mentioned that Hausa was included in CCNet. However, I didn't find the language code of `Hausa` in the dumped files and [fasttext lid's document](https://fasttext.cc/docs/en/language-identification.html#list-of-supported-languages).

**Comment by gwenzek** [comment]
Hi, in the XLM-R paper they used a Facebook internal LID model, which has support for Hausa.
The LID model isn't open source, and I'm not aware of plan to open source it.
But I'm currently working on releasing the data used in the XLM-R paper, which will contain the Hausa corpus.

**Comment by gwenzek** [comment]
Hi Li, I've added [dl_cc_100.py](https://github.com/facebookresearch/cc_net/blob/master/cc_net/tools/dl_cc_100.py) that will contains the Hausa. 
If you don't want run this yourself you can look at http://data.statmt.org/cc-100/, that have been released recently but I'm not 100% sure that you'll get the same results.

**Comment by donglixp** [comment]
@gwenzek  Thanks for the open-source effort! The corpus is very useful to the community.

**Comment by Hadjerkhd** [comment]
> Hi Li, I've added [dl_cc_100.py](https://github.com/facebookresearch/cc_net/blob/master/cc_net/tools/dl_cc_100.py) that will contains the Hausa.
> If you don't want run this yourself you can look at http://data.statmt.org/cc-100/, that have been released recently but I'm not 100% sure that you'll get the same results.

@gwenzek , is the data shared in `http://data.statmt.org/cc-100/`, the same used to pre-train XLM-R ? because when comparing the document sizes per language, in this web page and XLM-R paper, they are not the same values
Thanks
